### ISSUE TITLE
Move Examples out of package directory

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/mirage#106]
I think the convention for notebook examples is to keep them in the repo but outside of the package directory. This would mean moving `mirage/mirage/examples/` to `mirage/examples` - I imagine a quick fix.

**Comment by bhilbert4** [comment]
I can do that. I also need to re-run the notebooks so that the execution notes mention `mirage` rather than `nircam_simulator`. Just leaving a note here so that I remember.

**Comment by laurenmarietta** [comment]
Closed via #113
