### ISSUE TITLE
When a source position is too far from the specified field center position, mirage hangs.

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/mirage#111]
I have found that mirage hangs in catalog_seed_image.py if the input source sky coordinates are too far from the field position specified.  By mistake I had coordinates for stars in a sky field near the M4 globular cluster at position (245.924, -26.505) as the input star list, but put the RA/Dec positions in the .yaml file for a comparison field at the same galactic latitude away from the globular cluster at position (228.083, -40.352).  The code gets to the call 

pixelx, pixely = self.RADecToXY_astrometric(ra, dec, attitude_matrix, coord_transform)

in catalogue_seed_image.py for the first object on the list, but it then hangs up or at least takes a very long time.  I killed the python run after 1 hour.  The code had still not gotten the pixel (x,y) values for the first target.

**Comment by bhilbert4** [comment]
Fixed via a source distance filter, in #125
