### ISSUE TITLE
Share functions between classes/remove redundant functions

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/mirage#112]
i.e. calcFrameTime is present in catalog_seed_image as well as yaml_generator. No need to have it in both places. Update the code to have a single function somewhere and import it in other classes where it is needed. This will make maintenance much easier.

**Comment by laurenmarietta** [comment]
Maybe in somewhere like a `utils.py`?

**Comment by bhilbert4** [comment]
Also include the expand_env_var function in yaml_generator.

**Comment by bhilbert4** [comment]
This work has been completed.
