### ISSUE TITLE
Use logging

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/mirage#114]
I think a good long-term goal would be to start using the `logging` module for the simulator output, rather than using print statements. These logs could then be output to both `stdout` in the terminal and also saved to a file for later review. 

Here is Catherine Martlin's wiki page on logging for the JWQL project: https://github.com/spacetelescope/jwql/wiki/JWQL-Logging-Function:-The-Why's-and-The-How

**Comment by bhilbert4** [comment]
Logging has been implemented.
