### ISSUE TITLE
Update WebbPSF dependency to 0.7.1

### ISSUE THREAD

**Issue by shanosborne** [spacetelescope/mirage#137]
This needs to be done after WebbPSF 0.7.1 is released

**Comment by laurenmarietta** [comment]
Does pysynphot also need to be added?

**Comment by shanosborne** [comment]
Ah yes it does - I'll do that too

**Comment by mperrin** [comment]
Incidentally the next release of WebbPSF will probably be 0.8.0 rather than 0.7.1. The removal of Python 2.7 support is a substantial enough change that this deserves more than an 0.0.1 bump.

**Comment by bhilbert4** [comment]
Webbpsf version is currently set to 0.9.0.
