### ISSUE TITLE
Notebook not included in environment

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/mirage#164]
When running MIRAGE on the Linux environment I created on a server, I realized that `notebook` is not included in the environment yaml. Since we have notebook examples included in the repo, this is probably a good thing to include.

**Comment by laurenmarietta** [comment]
`astroquery` is also used in the OTE examples, and should probably be included.

**Comment by bhilbert4** [comment]
`astroquery` and `notebook` are now both included in the environment file. See #158.
