### ISSUE TITLE
Collect APT Programs for Testing

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/mirage#198]
I have put some OTE APT programs (the pointing and xml files) in this directory for us to use to test MIRAGE:

`/ifs/jwst/wit/mirage_data/test_programs`

Other test programs of interest should also be added here, so they are easily located in a shared space.

**Comment by Johannes-Sahlmann** [comment]
Thanks for posting the programs. Looks like `01069/NRC21_pid1069_2018_rev2.xml` is inconsistent, because it specifies `<CoordinatedParallel>true</CoordinatedParallel>` but it does not actually contain parallel observations.

**Comment by bhilbert4** [comment]
Oops. 1069 might have been my stripped down version of another APT file so that I could make yaml files. I'll try to dig up the original version.

**Comment by laurenmarietta** [comment]
I think I'll close this issue now, since we did collect more APT programs to integrate into the test suite.
