### ISSUE TITLE
Generate commissioning image for WFR3

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/mirage#212]
We received the following email from @obi-wan76 as a follow-up from the WFR2 quicklook tools splinter meeting:

> I was thinking about how feasible would be to get together before WFR3 (March) to compare results from the different tools discussed during our WFR2 splinter session. We could start by trying to simulate the observing strategy during Global Alignment 1 (large array PMSA, focus diversity images). I can provide the OPDs for these configurations and then the various tools could try to simulate the observations from the GA-1 APT program (APT: 1141). After this, we can perform a quick analysis to compare various PSFs quality measurements/criteria among the various tools. The general idea would be to test the tools against each other to discuss agreement/disagreement between simulations...  I think this would be a great opportunity not only for a preliminary comparison between tools but also as a way to keep fostering communication between the various groups.  

In preparation for WFR3, we should plan to generate images from Global Alignment that will ultimately be compared with other simulations from PyNRC and ComET. All of the GA images could then be analyzed using JWQL, FirstLook, and QUIP to explore how they differ, and what can be learned from those differences.

This is a long-term issue that depends on the completion of #142 at the very least, but an important goal to work towards.

**Comment by mperrin** [comment]
I'm going to say we can delete this issue, as WFR3 is in the past and we did not do this for that.
