### ISSUE TITLE
Inputs from the APT file can cause Mirage to crash

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/mirage#251]
I was trying to run a .yaml file generated by the APT to yaml interface in Mirage and the code told me that it could not open the parameter file.  (The message was "WARNING: unable to open" followed by the .yaml file name.  It is generated on line 2788 of catalog_seed_generator.py.)  There are two issues here in my opinion:

(1) the cause of the issue is a ":" in the label string of the observation.  I did not know that it was there as the observation is copied from one of the NIRISS CARS.  The APT to yaml conversion copies this label to the parameter file and the resulting line is

  observation_label: Confirmation: Imaging, NRM, GR700XD    # User-generated observation Label

This causes yaml to flag an error because of the second : on the line.  Since this parameter is not used in the code it is irritating that this causes the model to fail.  I would suppose that other such instances might happen in other parameters if a : is present.  The APT to yaml file conversion should screen out these cases in some way.

(2) When the code is unable to read the parameter file it calls sys.exit.  I think this is not the behaviour we want because when running a set of models from a series of parameter files the code will stop at this point whereas it would be better to exit in some other way so that the calculations can continue.  If I am running interactively in Python this kicks me out of the interpreter to the command line and I lose any variables that have been defined as well as having to reload the package when I go back into Python.  This is somewhat irritating, at least for me.  Is there a good reason to call sys.exit rather than just exit?  I think the latter will return one to the Python prompt.

**Comment by KevinVolkSTScI** [comment]
I looked online and I see that sys.exit and exit both do much the same thing.  Nonetheless, if an error is raised in the code that will not cause the end of a Python session, so I suggest that the code raise an error condition rather than exiting.

**Comment by bhilbert4** [comment]
You must have been running with a manually created/edited yaml file? Looking at the code in `yaml_generator`, there is already a check for colons in the proposal title. If they are there, they are replaced with a comma prior to writing out the yaml file.

In terms of avoiding this issue when reading in a manually-created yaml file, the only option I can think of would be a function that reads in the yaml file line by line and replaces/removes any colon after the first, before then moving on to loading the contents of the file into a yaml dictionary.

As for the sys.exit, I'll replace that with a properly raised exception.

**Comment by KevinVolkSTScI** [comment]
@bhilbert4 I believe that the cases where this has happened were all automatically generated and the offending line in the .yaml files were not changed by me after the generation.  I did go in and fix the dark ramp names because these were not being handled properly, and I might have also changed some of the other parameters used by the code, but not the title which just goes into the header.  It may be that the fix was put in after I had the issue last month.

**Comment by bhilbert4** [comment]
I made some changes in #259 to address this.

**Comment by bhilbert4** [comment]
Solved via #259
