### ISSUE TITLE
.upper() problem in imagingsimulator.create()

### ISSUE THREAD

**Issue by npirzkal** [spacetelescope/mirage#253]
Line 2552 of obs_generator calls .upper(). This causes problems with the latest versions of yaml files which contain numbers for the field primary_dither_type

**Comment by bhilbert4** [comment]
Problem was with only the direct and out of field exposures in WFSS mode. I updated the code such that when dither patterns are not defined, they should be set to NONE, which is what was already being done for the grism exposures. This fix is in #233

**Comment by bhilbert4** [comment]
Fix has been merged.
