### ISSUE TITLE
Feature Request: Spectroscopic simulations

### ISSUE THREAD

**Issue by pllim** [spacetelescope/mirage#261]
@eteq mentioned that it would be awesome if Mirage can simulate spectroscopic exposures. This is because currently it is not trivial to obtain such things for JWST data analysis software development. Simulated data here would not bound by ITAR nor EAR, which would be a plus.

**Comment by bhilbert4** [comment]
See #254. Under review at the moment.

**Comment by bhilbert4** [comment]
WFSS code has been merged into `master`.
