### ISSUE TITLE
support for NirspecMOS and MiriImaging template

### ISSUE THREAD

**Issue by stacchella** [spacetelescope/mirage#299]
Hi, 

as part of the NIRCam GTO, we do our imaging as parallels with NIRSpec and also with MIRI. Currently the APT xml reader does not support those templates. As an example, I've included one xml file that uses the NirspecMOS (and MiriMRS) template. Would it be possible to add those APT templates? Thank you for your consideration.

[1180_pa_41.xml.zip](https://github.com/spacetelescope/mirage/files/3204186/1180_pa_41.xml.zip)

@bd-j

**Comment by bhilbert4** [comment]
Sorry for the delayed response. 

Thanks for the suggestion. Parallel imaging with NIRSPec and MIRI was added to the repo not long ago, but only for a subset of the NIRSpec and MIRI observing modes. MIRI MRS should be recognized, but I don't think NIRSpec MOS is. I'll look into it and see if I can add something to cover MOS.

**Comment by stacchella** [comment]
It would be great to add something to cover MOS; thank you for looking into it!

**Comment by bhilbert4** [comment]
Resolved via #637
