### ISSUE TITLE
Header values of RA_V1, DEC_V1 are usually not correct

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/mirage#344]
The values of RA_V1, DEC_V1 are set to the target's RA, Dec which is incorrect in almost all cases because the target is usually located within an instrument aperture:
e.g. here https://github.com/spacetelescope/mirage/blob/ef140bd0e8cc86e7dec4b8dbc7cf34360bc9f673/mirage/ramp_generator/obs_generator.py#L2588

Instead RA_V1, DEC_V1 should be computed on the basis of the target coordinates and the target's V2,V3 location in combination with the specified `rotation`. It should probably be made more explicit what `rotation` refers to. Currently it is defined as " y axis rotation (degrees E of N)". It should be clarified if this is ROLL_REF or PA_V3.

**Comment by bhilbert4** [comment]
Solved in #346
