### ISSUE TITLE
Tilt-to-pixel scaling issue in segments_psfs.py

### ISSUE THREAD

**Issue by Skyhawk172** [spacetelescope/mirage#457]
While generating mosaics using unstacked segments we noticed that the SW and LW mosaics were different. In particular, the segment offsets on the LW data looked consistently scaled up from the SW data.  See attached.

We narrowed it down to the fact that the tilt-to-pixel scaling was only valid for the SW detectors. The fix should be easy to make, which I will provide as soon as possible.

Note that we confirmed that nominal MIRAGE SW and LW mosaics agree with each other.

![SW_vs_LW](https://user-images.githubusercontent.com/9323123/74470317-5227dc80-4e6c-11ea-9c18-4c41eb36d502.gif)

**Comment by bhilbert4** [comment]
Resolved via #462
