### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/mirage#48]
In order to make more clear that this is not a full-up instrument simulator, and due to the plans to add support for NIRISS, we need to rename the repo. This will necessitate a few changes in the code, mostly related to import statements. I believe I will have to ask the spacetelescope admins to actually do the renaming. I believe only they have the proper permissions.

Suggested new name: 
Multi-Instrument RAmp GEnerator (MIRAGE).

**Comment by laurenmarietta** [comment]
Closed via #113
