### ISSUE TITLE
Feature Function Request : Predict Execution Time

### ISSUE THREAD

**Issue by astroarshn2000** [spacetelescope/mirage#515]
Hi Bryan,

Is it possible to expedite the creation of a function in MIRAGE that predicts the execution time for simulations, as we have talked about earlier? Currently, my GRISM TSO simulations are taking an enormous amount of time to finish and some simulations run for a week and don't finish at all. Once we've got everything figured out, waiting a week is okay, but while we're testing, we need things to happen more rapidly.

Cheers,
Arsh

**Comment by bhilbert4** [comment]
Hi Arsh,
    I'll try to put something in soon. I also found what looks to be a logic flaw in the way the dispersed background is added. It looks like at the moment, if there is not a catalog of non-TSO sources that is added, the 2d dispersed background isn't created and added. I'll deal with both issues together. 

In the mean time, you should get the 2d dispersed background if you add a point source catalog, and the sources in that catalog can be outside the fov of the aperture. 

As for the execution time prediction though, that won't speed up the code at all. If you need a faster turnaround time, then it would probably best to reduce the number of integrations in your TSO exposure.
