### ISSUE TITLE
NIRISS PSFs in niriss/gridded_psf_library should be normalized to 1

### ISSUE THREAD

**Issue by dthatte** [spacetelescope/mirage#525]
The scaling factor for magnitude to count rate conversion is accounted for in utils.py, lines 721 to 729 and values in the photometry file for NRM and regular imaging. Therefore the PSFs in 
/ifs/jwst/wit/mirage_data/niriss/gridded_psf_library/ should be normalized to 1.

```
# For NIRISS AMI mode, the count rate values calculated need to be
# scaled by a factor 0.15/0.84 = 0.17857. The 0.15 value is the
# throughput of the NRM, while the 0.84 value is the throughput of the
# imaging CLEARP element that is in place in the pupil wheel for the
# normal imaging observations.
if observation_mode in ['ami', 'AMI']:
   count_scale = 0.15 / 0.84
else:
   count_scale=1.
```

For example niriss_nis_f480m_mask_nrm_fovp301_samp5_npsf1_predicted_realization0_nis.fits is normalized to 0.15057966144945326 and niriss_nis_f480m_clearp_fovp301_samp5_npsf1_predicted_realization0_nis.fits is normalized to 0.8357325488232911 .

When I used the above NRM PSF the count rate in the seed image was too low because the NRM throughput was accounted for twice, once because of the scaling factor and the second time because of normalization to ~0.15.

I compared the count rate with a calculation for the same source and exposure parameters in the JWST ETC. The count rate in the central pixel was very close to the count rate in the JWST ETC (displayed in the attached screenshot) after normalizing the NRM PSF to 1.

<img width="1567" alt="AB_Dor_f480m_countrate_etc_ami" src="https://user-images.githubusercontent.com/5454765/88343108-a209aa00-cd0e-11ea-9d41-0d1fdb214ef1.png">
KevinVolkSTScI suggested to check if NIRCam PSFs for the specialized phase masks have the right count rate with the current set-up.

**Comment by bhilbert4** [comment]
Duplicate. Closing this in favor of #526
