### ISSUE TITLE
The EXP_TYPE for NRM + Filter observations is incorrect

### ISSUE THREAD

**Issue by dthatte** [spacetelescope/mirage#540]
The EXP_TYPE for NRM + Filter observations should be changed to NIS_AMI.
Currently AMI data that uses NRM has EXP_TYPE set to NIS_IMAGE as shown below.
`EXP_TYPE= 'NIS_IMAGE'          / Type of data in the exposure`

When this data is run through the JWST pipeline it applies some steps that would have been correctly skipped if the EXP_TYPE was NIS_AMI.

**Comment by bhilbert4** [comment]
Thanks for catching this. I have a fix in place. I'll merge it as soon as the tests pass.
