### ISSUE TITLE
Option to fetch fewer darks for simple testing

### ISSUE THREAD

**Issue by gbrammer** [spacetelescope/mirage#562]
Feature request: provide an option in ``downloader`` to fetch only a limited set of dark reference files rather than forcing the user to download  hundreds of GB of reference files just to get a test up and running!

Thanks!

**Comment by bhilbert4** [comment]
Are you thinking of an option that retrieves just a single dark file for each detector? Or have the user specify a detector and download a single dark for only that detector? While developing, my thought was that users will generally want to be able to create simulations of all detectors, or at least all detectors of a given module. 

Also, the raw darks are smaller, and faster to download, but that time savings is pretty much lost by then having to run the calibration pipeline on those files.

**Comment by gbrammer** [comment]
Yes, I think the main thing I had in mind was single darks for each detector.  That already decreases the download size by a factor of 10.
