### ISSUE TITLE
Update needed for keywords in catalog_generator Documentation 

### ISSUE THREAD

**Issue by mtakahiro** [spacetelescope/mirage#617]
Two keywords, filter and mag_sys, in the catalog_generator module seem to have been changed to filter_name and magnitude_system, respectively.

I would appreciate if the documentation here can be updated accordingly.
https://mirage-data-simulator.readthedocs.io/en/latest/catalog_creation.html?highlight=catalog_generator

Thanks!

**Comment by bhilbert4** [comment]
Good catch! Thanks! I've just submitted a PR to fix that documentation page.

**Comment by mtakahiro** [comment]
Looks good to me! Thank you!
