### ISSUE TITLE
Develop unit tests for different APT files/templates

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/mirage#64]
Create one APT file for each instrument that can be simulated (for now, NIRCam and NIRISS), with all necessary templates in each file.

Ultimately, compare `.yaml` output with some kind of reference `.yaml`.

Use the STScI package template to model test structure for continuous integration:
https://github.com/spacetelescope/stsci-package-template

**Comment by Johannes-Sahlmann** [comment]
Functional example for the template's CI via Travis: https://github.com/spacetelescope/nrm_analysis

**Comment by laurenmarietta** [comment]
Though unit testing does still need to be more robustly developed, this particular system test for APT templates has been developed.
