### ISSUE TITLE
Flux normalization is off

### ISSUE THREAD

**Issue by eas342** [spacetelescope/mirage#648]
I ran the NIRCam TSO examples notebook here and the flux normalization appears way off:
https://github.com/spacetelescope/mirage/blob/master/examples/NIRCam_TSO_examples.ipynb

The image is way saturated on the first group. Here are the versions of stuff I have:
* mirage '1.3.4.dev467+g7e275b7'
* NIRCam-Gsim 1.5 and latest development version both had the problem
* GRISM_NIRCAM/V2 data

<img width="1360" alt="Screen Shot 2021-03-23 at 7 37 43 PM" src="https://user-images.githubusercontent.com/234377/112246136-68779e80-8c0f-11eb-93de-0cd74089f311.png">

Any other package versions or data files I should check?

**Comment by bhilbert4** [comment]
@NorPirzkal

**Comment by bhilbert4** [comment]
@eas342 how do the fluxes look in the undispersed seed image?  And are you providing an SED for the target with values and units that are correct? I'm assuming that this is a case that used to work and that inputs haven't changed, but I just wanted to be sure.

**Comment by eas342** [comment]
The `tso_grism_sources_F444W_GRISMR_final_seed_image` between an old mirage run and the new one look about the same (other than different image dimensions). The `_dispersed_seed_images.fits` is ~40,000 times larger in the new mirage run as compared to the old one if that's a clue. I applied normalization with the values from the notebook linked at the top Johnson K=9.06 and then again with object_f444w_mag = 9.0.

**Comment by NorPirzkal** [comment]
Hi Everett,

What are the range of values in your input spectrum and what units are you using?
What do you get if you do not use your own spectrum and instead let Mirage use the photometry to determine a low res SED?

N

On Mar 24, 2021, at 2:50 PM, Everett Schlawin ***@***.******@***.***>> wrote:



The tso_grism_sources_F444W_GRISMR_final_seed_image between an old mirage run and the new one look about the same (other than different image dimensions). The _dispersed_seed_images.fits is ~40,000 times larger in the new mirage run as compared to the old one if that's a clue. I applied normalization with the values from the notebook linked at the top Johnson K=9.06 and then again with object_f444w_mag = 9.0.

**Comment by eas342** [comment]
Thanks for looking into this @NorPirzkal ! Some of what you need might be hidden from foolish users like me under the hood of `mirage`. In the beginning of the example mirage notebook, it sets wavelength units to microns and flux units to `flam`, which ranges from 0 to 1e-13. Can you help point me to which file or input would be useful to check the counts in for NIRCam_Gsim? There is a `source_sed_file_from_ptsrcs_and_test_grism_tso_sed_file_wasp79.hdf5`

**Comment by eas342** [comment]
I installed everything on a compute cluster to test this and the problem recurs. One thing I was wondering if there could be an issue with my reference data? I did copy all of my MIRAGE_DATA, GRISM_NIRCAM/V2 and CDBS data from the other server.

**Comment by eas342** [comment]
I also tried rolling back NIRCAM_GSIM to version 1.4b1 along with using GRISM_NIRCAM/V1 and the first group is still way saturated in the simulation. So, the solution probably needs a more intelligent approach of testing the dispersion step than my wild guesses about package versions and grism data.

**Comment by eas342** [comment]
Any suggestions? Fortunately a student kept older versions of mirage from early 2020 before upgrading so we will use that for now.

**Comment by bhilbert4** [comment]
I'm trying a test case now. Using python 3.8 I got a slew of multiprocessing errors during dispersion. I backed down to python 3.6 and dispersion is working, but is slow. I'll report back when it finishes up.

**Comment by eas342** [comment]
Yay! The normalization problems looks to be fixed by https://github.com/npirzkal/NIRCAM_Gsim/commit/39ea72cbeea0e378c120a7b3c82a7fe9bd349565
