### ISSUE TITLE
Ramp generator stitching file segments incorrectly

### ISSUE THREAD

**Issue by hover2pi** [spacetelescope/mirage#677]
With long observations `obs_generator` seems to be saving file segments incorrectly. For example, a 6 group, 320 integration simulation of NIRISS SOSS data generates two segments of data of 213 and 107 integrations. Since this data contains a planetary transit that happens to fall right in the middle of the file split, the reduced data shows this problem.

![](https://files.slack.com/files-pri/TQN4UL0NM-F0210AEJMEX/screen_shot_2021-05-05_at_1.47.43_pm.png)

A quick look at the saved seed image shows this does not appear in the raw data.

![](https://files.slack.com/files-pri/TQN4UL0NM-F0216R629L4/screen_shot_2021-05-05_at_3.59.20_pm.png)

So perhaps the `seg002` file, which has no visible transit, isn't being saved properly. One theory is that `obs_genetrator` is slicing the seed image from the beginning of the observation for all segments.

**Comment by bhilbert4** [comment]
Hmm. My first thought is that this is SOSS specific somehow. NIRCam TSO observations that are split into segments are stitched back together correctly from what I have seen. I wonder if this is related to that if/else clause in #671, in obs_generator.py around line 200. Maybe I can try to dig up a TSO observation and we can compare the intermediate files (seed image files, darks, etc)?

**Comment by hover2pi** [comment]
Yeah, I'll put the error catch back in there and try to fix it another way to see if the issue is resolved.

**Comment by eas342** [comment]
@hover2pi , did you end up resolving this?

**Comment by hover2pi** [comment]
Yes!
