### ISSUE TITLE
No ra_ref,dec_ref keywords in pointing_dictionary when creating catalogs

### ISSUE THREAD

**Issue by micaelabagley** [spacetelescope/mirage#694]
I'm getting a KeyError when using `create_catalog` to query for point sources in my simulated FOV with an input APT pointing and xml file.

I'm using Mirage v2.0.2, and simulating NIRCam Imaging mode.

The issue is that there are no keywords `ra_ref` or `dec_ref` in `pointing_dictionary` (there are `ra` and `dec`).

My call to `create_catalog`:
```
catalog_out = create_catalog.for_proposal(xml_file, pointing_file,
                                          point_source=True, extragalactic=False,
                                          catalog_splitting_threshold=0.12,
                                          out_dir=out_dir, save_catalogs=True)
```
The calls for `ra_ref` and `dec_ref` are in `mirage.catalogs.create_catalogs.for_proposal()`, lines 153-154, 163, 194-195, 216-217.

From what I can tell, the `*_ref` keywords are relevant for the WFSS mode. Is it appropriate for me to replace these `ra_ref` and `dec_ref` with `ra` and `dec`, respectively, in `for_proposal()`?

**Comment by bhilbert4** [comment]
Someone else just mentioned this bug to me the other day. Looking at the code it's not clear to me how the ra_ref and dec_ref entries are not being populated. What program is this for? I want to download the APT file and try to recreate the error.

**Comment by micaelabagley** [comment]
This is for CEERS (1345), but most of the NIRCam imaging is done in parallel. I've created a separate apt file and copied the pointing info from the CEERS aptx. I'm currently working on a stripped down version with just a single NIRCam pointing (called CEERS5). 

I'm attaching the NIRCam-only apt file (CEERS5_NIRCam.aptx), the xml file (CEERS5_NIRCam.xml), and **edited** pointing file (CEERS5_NIRCam.pointing) and the CEERS pointing file for this pointing (CEERS5.pointing)
[CEERS5.zip](https://github.com/spacetelescope/mirage/files/6673205/CEERS5.zip)

**Comment by bhilbert4** [comment]
This should now be fixed in the master branch of the repository. I'm single-parenting tomorrow, but I'll try to find some time to create a new release and put it up on pypi.
