### ISSUE TITLE
Simulated galaxies appear to be flipped

### ISSUE THREAD

**Issue by x12red** [spacetelescope/mirage#766]
Hi all, 

I've just noticed that simulated galaxies have a different position angle compared to what I give as input.
Is there a way to fix it?

Thanks in advance!

**Comment by bhilbert4** [comment]
Hmm yes. I think I see what you mean. If your PAV3 value is non-zero, it looks like the galaxies are rotated in the wrong direction and end up 90 degrees from where they should be. I'll work on fixing that. In the meantime, try adding or subtracting 90 degrees from your galaxy position angles for observations with PAV3 != 0.
