### ISSUE TITLE
`ValueError` upon import when attempting reference file download

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/mirage#804]
@codebreaker2 has the following issue when following an example in the documentation:

> I am following the instructions given here: https://mirage-data-simulator.readthedocs.io/en/latest/reference_files.html
>
> Please provide advice on how to fix the error I'm getting. 
>
> Thanks, 
> Crystal 
> 
> p.s. 
>
> Here's the result after the first step. 
>
> ```shell
> (base) tango:Users cmartin$ source activate mirage 
> (mirage) tango:Users cmartin$ python --version 
> Python 3.9.13 
> (mirage) tango:Users cmartin$ ipython 
> ```
> ```python
> Python 3.9.13 (main, Aug 25 2022, 18:29:29) 
> Type 'copyright', 'credits' or 'license' for more information 
> IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help. 
> In [1]: from mirage.reference_files import downloader 
> --------------------------------------------------------------------------- 
> PermissionError Traceback (most recent call last) 
> File ~/opt/miniconda3/envs/mirage/lib/python3.9/logging/config.py:564, in DictConfigurator.configure(self) 
>     563 try: 
> --> 564 handler = self.configure_handler(handlers[name]) 
>     565 handler.name = name 
> 
> 
> . 
> . 
> . 
> ValueError: Unable to configure handler 'file' 
> ```

**Comment by bhilbert4** [comment]
Strange. I just created a new python 3.9 environment with a fresh install of mirage, and I'm able to run that import statement with no problems. 

Could there have been some problem with the environment creation? It might be worth starting over to see if it happens again.

```
conda create -n mirage python=3.9 -y
conda activate mirage
pip install mirage
```

**Comment by bhilbert4** [comment]
Closing in favor of identical Help Desk ticket
