### ISSUE TITLE
Some errors in the niriss_subarrarys.list file in config.

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/mirage#95]
An update to the niriss_subarrays.list file is needed.  There was an error in the bounds for SUBSTRIP256 and the SUB80 subarray needed to be replaced by the AMI1 to AMI4 cases as in the SIAF file.  Branch niriss-subarray-fix has the corrected subarray file and no other changes.

**Comment by laurenmarietta** [comment]
Now that `pysiaf` is public, we could potentially fix this for NIRISS, and the other instruments, by using `pysiaf` to get the information for each subarray aperture directly from the SIAF file.

**Comment by bhilbert4** [comment]
Updated NIRISS subarray list provided in #143. I believe the errors referred to above were fixed in #121
